# WhatATheme
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Joyce Zhou
# Description of the Site
description: A creator's portfolio 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jowiece844240@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: xinyi-joyce-zhou
github_username:  joycethecreator
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Joyce Zhou
# URL for the Image of the Author
author-image: /assets/images/profile.png
# 60 Words About the Author
author-about: Hi there, I'm Joyce. Welcome to my digital playground - where I turn ideas into interactive and visual experiences. I am a graphic programmer, film maker, teacher, and photographer, all with passion, perpetual curiosity, and an eye for elegance and ingenuity in both code and aesthetics.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/joycethecreator

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-archives

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive-tag
  permalinks:
    tag: /tag/:name/

